### ISSUE TITLE
Rater is not updating for some reason

### ISSUE THREAD

**Issue by r3wt** [NdYAG/react-rater#29] opened 2019-08-26 17:07 UTC
![image](https://user-images.githubusercontent.com/4483325/63708364-d07abe80-c7f9-11e9-8346-5d8b28198a39.png)
As you can see in the image, an aggegration function updates the static read only rater, but for some reason this rater is not updating, even though the props show that a rating is provided. I'm not sure what is happening, any ideas?

code is simple its just:
```js
<Rater total={5} interactive={false} rating={this.state.rating} />
```

Edit: after looking at the code of this library, i am suspecting this is due to `UNSAFE_componentWillReceiveProps()` being the only method that the component updates.

**Comment by NdYAG** [comment] 2019-09-18 08:44
Hi @r3wt Thanks for reporting the issue. Sorry for not responding earlier. 

For the case above, there could be another fix. If you want to force the static rater to re-render,  try set a `key` prop with rating as its value. For the code, I will consider update `UNSAFE_componentWillReceiveProps ` and move to `getDerivedStateFromProps`. But it's expected to work if rating has changed, no matter whether the rater is interactive or not.

Without more information like the version you're using and more code, I'm cannot locate the cause of this issue. I'll close this first, but feel free to reopen it anytime.

**Closed by NdYAG** 2019-09-18 08:44 UTC
